// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
import { createImage, renderWith } from "obix-core-component";
export { createImage } from "obix-core-component";
export type { ImageConfig, ImageDecoding, ImageLoading, ImageState } from "obix-core-component";
export const renderImage = renderWith(createImage);
